name: DEPLOY_TO_SERVER_VIA_SSH

on:
  push:
    branches: ['nothing']

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          envs: DB_NAME, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, SLACK_WEBHOOK_URL, DISCORD_WEBHOOK_URL
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export DB_NAME=$DB_NAME
            export DB_HOST=$DB_HOST
            export DB_PORT=$DB_PORT
            export DB_USER=$DB_USER
            export DB_PASSWORD=$DB_PASSWORD
            export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
            export DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL
            cd $HOME/Projects/${{ github.event.repository.name }}
            git pull origin main
            sh ./scripts/create_dotenv.sh
            sh ./scripts/update_packages.sh
