name: DEPLOY_TO_SERVER_VIA_SSH

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          envs: DB_NAME, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, SLACK_WEBHOOK_URL
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            touch .env
            echo "DB_NAME=$DB_NAME" >> .env
            echo "DB_HOST=$DB_HOST" >> .env
            echo "DB_PORT=$DB_PORT" >> .env
            echo "DB_USER=$DB_USER" >> .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            echo "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL" >> .env
            mv ./.env $HOME/Projects/${{ github.event.repository.name }}
            cd $HOME/Projects/${{ github.event.repository.name }}
            git pull origin main
            sh update_packages.sh